# Generated by Django 2.0.3 on 2018-03-26 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoalgo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
